'use strict';
'require form';
'require nezha-agent.import-parser as importParser';
'require rpc';
'require ui';
'require view';

var callServiceList = rpc.declare({
	object: 'service',
	method: 'list',
	params: [ 'name' ],
	expect: { '': {} }
});

function getServiceStatus() {
	return L.resolveDefault(callServiceList('nezha-agent'), {}).then(function(res) {
		var instances = res['nezha-agent'] && res['nezha-agent'].instances;
		var running = false;

		Object.keys(instances || {}).forEach(function(name) {
			running = running || instances[name].running === true;
		});

		return running;
	});
}

function notify(message, style) {
	var node = ui.addNotification(null, E('p', {}, message), style);
	var button = node.querySelector('button');

	if (button)
		button.addEventListener('click', function() {
			if (node.parentNode)
				node.parentNode.removeChild(node);
		});
}

return view.extend({
	load: function() {
		return getServiceStatus();
	},

	render: function(running) {
		var m, s, o, commandOption, serverOption, secretOption, tlsOption, uuidOption;

		m = new form.Map('nezha-agent', _('Nezha Agent'),
			_('Configure and manage the Nezha monitoring agent.'));

		s = m.section(form.NamedSection, 'main', 'agent', _('Agent Settings'));
		s.anonymous = true;
		s.addremove = false;

		o = s.option(form.DummyValue, '_status', _('Service status'));
		o.rawhtml = true;
		o.cfgvalue = function() {
			return running
				? '<strong style="color:green">%s</strong>'.format(_('Running'))
				: '<strong style="color:red">%s</strong>'.format(_('Not running'));
		};

		o = s.option(form.Flag, 'enabled', _('Enable'));
		o.rmempty = false;

		commandOption = s.option(form.TextValue, '_install_command', _('V1 installation command'));
		commandOption.rows = 4;
		commandOption.rmempty = true;
		commandOption.cfgvalue = function() { return ''; };
		commandOption.write = function() {};
		commandOption.remove = function() {};
		commandOption.description = _('Paste the Linux installation command generated by the Nezha V1 dashboard. The command is parsed locally and is not saved.');

		o = s.option(form.Button, '_parse_install_command', _('Import installation command'));
		o.inputstyle = 'apply';
		o.inputtitle = _('Parse and fill');
		o.onclick = function(ev, section_id) {
			var parsed;

			try {
				parsed = importParser.parseInstallCommand(commandOption.formvalue(section_id) || '');
			} catch (e) {
				notify(_('Unable to parse the installation command. Ensure it contains valid NZ_SERVER and NZ_CLIENT_SECRET values.'), 'error');
				return;
			}

			serverOption.getUIElement(section_id).setValue(parsed.server);
			secretOption.getUIElement(section_id).setValue(parsed.clientSecret);
			if (parsed.tls != null)
				tlsOption.getUIElement(section_id).setValue(parsed.tls);
			uuidOption.getUIElement(section_id).setValue(parsed.hasUUID ? parsed.uuid : '');
			notify(_('Installation command parsed. Review the values, then save and apply the configuration.'), 'info');
		};

		o = s.option(form.DummyValue, 'config_file', _('Configuration file'));
		o.default = '/etc/nezha-agent/config.yml';

		serverOption = s.option(form.Value, 'server', _('Dashboard server'));
		serverOption.description = _('Server address in host:port format.');
		serverOption.placeholder = 'monitor.example.com:5555';
		serverOption.rmempty = false;

		secretOption = s.option(form.Value, 'client_secret', _('Client secret'));
		secretOption.password = true;
		secretOption.rmempty = false;

		tlsOption = s.option(form.Flag, 'tls', _('Enable TLS'));
		tlsOption.default = '0';

		uuidOption = s.option(form.Value, 'uuid', _('Agent UUID'));
		uuidOption.rmempty = true;
		uuidOption.description = _('Leave empty to generate a new UUID when the configuration is applied.');
		uuidOption.validate = function(section_id, value) {
			return !value || !/[\s\x00-\x1f\x7f]/.test(value)
				? true
				: _('UUID must not contain whitespace or control characters.');
		};

		o = s.option(form.Flag, 'insecure_tls', _('Skip TLS verification'));
		o.depends('tls', '1');

		o = s.option(form.Flag, 'disable_auto_update', _('Disable agent auto-update'));
		o.default = '0';

		o = s.option(form.Flag, 'disable_force_update', _('Disable forced updates'));

		o = s.option(form.Flag, 'disable_command_execute', _('Disable remote command execution'));

		o = s.option(form.Flag, 'disable_nat', _('Disable NAT traversal'));

		o = s.option(form.Flag, 'disable_send_query', _('Disable network query tasks'));

		o = s.option(form.Value, 'report_delay', _('Report interval'));
		o.datatype = 'range(1,4)';
		o.default = '3';
		o.description = _('Status reporting interval in seconds, from 1 to 4.');

		o = s.option(form.DynamicList, 'custom_ip_api', _('Custom IP APIs'));
		o.datatype = 'url';
		o.rmempty = true;
		o.placeholder = 'https://api.example.com/ip';
		o.description = _('Add the API domains to the direct-connect rules of OpenClash, PassWall, or other proxy software to obtain the real public IP address.');

		return m.render();
	}
});
